name: ej
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - geopandas>=0.14
  - rasterio
  - pyogrio
  - fiona
  - shapely
  - pyproj
  - numpy
  - pandas
  - scipy
  - rasterstats
  - matplotlib
  - mapclassify
  - jupyterlab
  - ipykernel
  - boto3
  - botocore